version: '3.9'

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    container_name: front
    depends_on:
      - back

  back:
    build: ./back
    ports:
      - "3001:3001"
    container_name: back


